directories:
  output: release
  buildResources: build
appId: com.nebula.app
productName: Nebula
icon: build/icon
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - '!node_modules'
      - '!src'
      - '!electron'
      - '!*.ts'
      - '!*.tsx'
mac:
  target:
    - target: zip
      arch:
        - arm64
        - x64
  category: public.app-category.graphics-design
dmg:
  title: Nebula
  background: null
  window:
    width: 540
    height: 380
  contents:
    - x: 410
      'y': 230
      type: link
      path: /Applications
    - x: 130
      'y': 230
      type: file
win:
  target: nsis
linux:
  target: AppImage
electronVersion: 28.3.3
